FROM python:3.8-slim-buster as base
FROM base as builder
FROM base

# RUN mkdir -p /app
# WORKDIR /app 

#setup folder
COPY ./ktmodel-standard        /ktmodel
WORKDIR /ktmodel
# COPY ./ktmodel/app.py .


# initialize environment
RUN pip install awslambdaric --no-cache
COPY ./ktmodel-standard/r.txt ./requirements.txt 
RUN pip install -r ./requirements.txt --no-cache

ENTRYPOINT [ "python", "-m", "awslambdaric" ]
CMD ["app.handler"]
